<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <Target Name="CopyDLLs" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)$(ProjectName).dll" DestinationFolder="$(MD_NET6_DIRECTORY)\Mods" />
    <Message Text="Copied DLL -&gt; $(MD_NET6_DIRECTORY)\Mods\$(ProjectName).dll" Importance="High" />
  </Target>

  <Target Name="CopyMod" AfterTargets="Repack" Condition="'$(WORKER)' != 'GitHub'">
      <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="$(GameFolder)\Mods" />
      <Message Text="Copied assembly to '$(GameFolder)\Mods\$(ProjectName).dll'" Importance="High" />
  </Target>

  <Target Name="WarnDeprecatedPath" AfterTargets="Build" Condition="!Exists('$(MD_DIRECTORY)')">
      <Message Text="Warning: MD_NET6_DIRECTORY is no longer in use. Please remove the environment variable and run SetPath.cmd again." Importance="High" />
  </Target>

  <ItemGroup>
    <Compile Remove="Assets\Stickers\Pack1\**" />
    <EmbeddedResource Remove="Assets\Stickers\Pack1\**" />
    <None Remove="Assets\Stickers\Pack1\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Stickers\annoyed.gif" />
    <None Remove="Assets\Stickers\cooing.gif" />
    <None Remove="Assets\Stickers\envy.gif" />
    <None Remove="Assets\Stickers\failed.gif" />
    <None Remove="Assets\Stickers\flipped.gif" />
    <None Remove="Assets\Stickers\foundle.gif" />
    <None Remove="Assets\Stickers\good_night.gif" />
    <None Remove="Assets\Stickers\jump_kick.gif" />
    <None Remove="Assets\Stickers\lazily.gif" />
    <None Remove="Assets\Stickers\onlooker.gif" />
    <None Remove="Assets\Stickers\rich.gif" />
    <None Remove="Assets\Stickers\shock.gif" />
    <None Remove="Assets\Stickers\sob.gif" />
    <None Remove="Assets\Stickers\speechless.gif" />
    <None Remove="Assets\Stickers\stay_away.gif" />
    <None Remove="Assets\Stickers\zombie.gif" />
    <None Remove="Assets\UI\Achievements.png" />
    <None Remove="Assets\UI\Awaiting.png" />
    <None Remove="Assets\UI\Back.png" />
    <None Remove="Assets\UI\Cross.png" />
    <None Remove="Assets\UI\Friends.png" />
    <None Remove="Assets\UI\Lobbies.png" />
    <None Remove="Assets\UI\Lobby.png" />
    <None Remove="Assets\UI\MainMenu.png" />
    <None Remove="Assets\UI\Navigation\Play.png" />
    <None Remove="Assets\UI\Navigation\Playlist.png" />
    <None Remove="Assets\UI\PcSprButton.png" />
    <None Remove="Assets\UI\People.png" />
    <None Remove="Assets\UI\Profile.png" />
    <None Remove="Assets\UI\Refresh.png" />
    <None Remove="Assets\UI\Settings.png" />
    <None Remove="Assets\UI\Statuses\InBattle.png" />
    <None Remove="Assets\UI\Statuses\InLobby.png" />
    <None Remove="Assets\UI\Statuses\Offline.png" />
    <None Remove="Assets\UI\Statuses\Online.png" />
    <None Remove="Localization\English.json" />
    <None Remove="Localization\Japanese.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\UI\Back.png" />
    <EmbeddedResource Include="Assets\UI\Banners\Achievements.png" />
    <EmbeddedResource Include="Assets\UI\Awaiting.png" />
    <EmbeddedResource Include="Assets\UI\Banners\Friends.png" />
    <EmbeddedResource Include="Assets\UI\Banners\Lobbies.png" />
    <EmbeddedResource Include="Assets\UI\Banners\Lobby.png" />
    <EmbeddedResource Include="Assets\UI\Banners\MainMenu.png" />
    <EmbeddedResource Include="Assets\UI\Cross.png" />
    <EmbeddedResource Include="Assets\UI\Navigation\Globe.png" />
    <EmbeddedResource Include="Assets\UI\Navigation\PcSprButton.png" />
    <EmbeddedResource Include="Assets\UI\Navigation\People.png" />
    <EmbeddedResource Include="Assets\UI\Banners\Profile.png" />
    <EmbeddedResource Include="Assets\UI\Navigation\Play.png" />
    <EmbeddedResource Include="Assets\UI\Navigation\Playlist.png" />
    <EmbeddedResource Include="Assets\UI\Refresh.png" />
    <EmbeddedResource Include="Assets\UI\RinRich.png" />
    <EmbeddedResource Include="Assets\UI\Banners\Settings.png" />
    <EmbeddedResource Include="Assets\UI\Statuses\InBattle.png" />
    <EmbeddedResource Include="Assets\UI\Statuses\InLobby.png" />
    <EmbeddedResource Include="Assets\UI\Statuses\Offline.png" />
    <EmbeddedResource Include="Assets\UI\Statuses\Online.png" />
    <EmbeddedResource Include="Localization\ChineseS.json" />
    <EmbeddedResource Include="Localization\ChineseT.json" />
    <EmbeddedResource Include="Localization\English.json" />
    <EmbeddedResource Include="Localization\Japanese.json" />
    <EmbeddedResource Include="Localization\ProfanityTrieList.txt" />
  </ItemGroup>

  <ItemGroup>
    <None Include="UI\NavigationButtons\PlayButton.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.45">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Stickers\Default\" />
  </ItemGroup>
</Project>
